In [ ]:
# ==========================================================
# IMPORTS
# ==========================================================

import os
import numpy as np
import pandas as pd

In [ ]:
# ==========================================================
# PATHS
# ==========================================================

MASTER_PIPELINE = "/content/drive/MyDrive/Exoplanet_Dataset/08_Master_Pipeline/Master_Pipeline.csv"

PHYSICS_V2 = "/content/drive/MyDrive/Exoplanet_Dataset/10_Physics_Features_V2/Physics_Features_V2.csv"


OUTPUT_FOLDER = "/content/drive/MyDrive/Exoplanet_Dataset/11_Training_Dataset_V2"


os.makedirs(

    OUTPUT_FOLDER,

    exist_ok=True

)

In [ ]:
# ==========================================================
# LOAD DATASETS
# ==========================================================

master = pd.read_csv(

    MASTER_PIPELINE

)

physics = pd.read_csv(

    PHYSICS_V2

)

print("="*60)
print("MASTER PIPELINE")
print("="*60)

print(master.shape)

print()

print("="*60)
print("PHYSICS FEATURES V2")
print("="*60)

print(physics.shape)

============================================================
MASTER PIPELINE
============================================================
(1172, 10)

============================================================
PHYSICS FEATURES V2
============================================================
(1172, 15)

In [ ]:
print(master.columns.tolist())

['TIC_ID', 'Label', 'Number_of_Sectors', 'Best_Sector', 'period_days', 'duration_days', 'epoch_days', 'bls_depth', 'bls_power', 'peak_sigma']

In [ ]:
print("=" * 70)
print("MASTER PIPELINE")
print("=" * 70)

print()

print("Rows    :", len(master))
print("Columns :", len(master))

print()

print(master.columns.tolist())

======================================================================
MASTER PIPELINE
======================================================================

Rows    : 1172
Columns : 1172

['TIC_ID', 'Label', 'Number_of_Sectors', 'Best_Sector', 'period_days', 'duration_days', 'epoch_days', 'bls_depth', 'bls_power', 'peak_sigma']

In [ ]:
# ==========================================================
# LOAD TRANSIT FEATURES
# ==========================================================

TRANSIT_FEATURES = "/content/drive/MyDrive/Exoplanet_Dataset/09_Transit_Features/Transit_Features.csv"

transit_features = pd.read_csv(

    TRANSIT_FEATURES

)

print("=" * 70)
print("TRANSIT FEATURES")
print("=" * 70)

print()

print("Rows    :", len(transit_features))
print("Columns :", len(transit_features))

print()

display(transit_features.head())

======================================================================
TRANSIT FEATURES
======================================================================

Rows    : 1172
Columns : 1172

,TIC_ID,depth_ppm,T_tot_hours,T_in_hours,duration_phase,ingress_phase,red_chi2,rms_resid
0,100100829,6966.443066,2.348209,0.523077,0.103831,0.023129,1.294422,0.006112
1,1001477809,1659.900328,4.239923,0.203342,0.023072,0.001107,0.946671,0.003261
2,100389539,5855.195047,3.059378,0.379115,0.029782,0.003691,1.260850,0.002054
3,10048801,1001.794239,4.282757,1.068869,0.048227,0.012036,1.804031,0.000583
4,100589632,1818.380793,2.197297,0.704832,0.023197,0.007441,0.946925,0.001957

In [ ]:
print("=" * 70)
print("TRANSIT FEATURES")
print("=" * 70)

print()

print("Rows    :", len(transit_features))
print("Columns :", len(transit_features))

print()

print(transit_features.columns.tolist())

======================================================================
TRANSIT FEATURES
======================================================================

Rows    : 1172
Columns : 1172

['TIC_ID', 'depth_ppm', 'T_tot_hours', 'T_in_hours', 'duration_phase', 'ingress_phase', 'red_chi2', 'rms_resid']

In [ ]:
# ==========================================================
# BUILD TRAINING DATASET V2
# ==========================================================

training_dataset_v2 = (

    master

    .merge(

        transit_features,

        on="TIC_ID",

        how="inner"

    )

    .merge(

        physics,

        on="TIC_ID",

        how="inner"

    )

)

print("=" * 70)
print("TRAINING DATASET V2")
print("=" * 70)

print()

print("Rows    :", len(training_dataset_v2))
print("Columns :", len(training_dataset_v2.columns))

print()

display(training_dataset_v2.head())

======================================================================
TRAINING DATASET V2
======================================================================

Rows    : 1172
Columns : 31

,TIC_ID,Label,Number_of_Sectors,Best_Sector,period_days,duration_days,epoch_days,bls_depth,bls_power,peak_sigma,...,secondary_depth,secondary_snr,duty_cycle,oot_rms,transit_rms,shape_rmse,transit_skewness,transit_kurtosis,transit_mad,transit_iqr
0,100100829,EB,3,69,0.942324,0.075,3182.749443,0.007126,928.753290,13.017379,...,584.814466,0.096849,0.103831,0.005761,0.006450,0.009890,-0.193433,0.170547,0.004188,0.008398
1,1001477809,False Positive,4,48,7.656943,0.168,2616.800708,0.001701,30.981110,5.724197,...,0.000000,0.000000,0.023072,0.008116,0.008817,0.009999,0.017202,1.211668,0.004985,0.009937
2,100389539,Planet,2,88,4.280297,0.114,3693.099793,0.005744,2436.410323,14.040970,...,253.630337,0.139124,0.029782,0.001933,0.002059,0.002368,0.114596,-0.136550,0.001398,0.002800
3,10048801,EB,2,47,3.700200,0.141,2583.045512,0.000936,1420.646948,9.640867,...,10.394129,0.017860,0.048227,0.000564,0.000582,0.000704,0.317949,0.752866,0.000374,0.000746
4,100589632,False Positive,1,87,3.946741,0.066,3665.759898,0.001609,75.715224,10.109563,...,96.806526,0.050277,0.023197,0.001926,0.001849,0.002397,-0.084457,-0.230016,0.001135,0.002265

In [ ]:
OUTPUT_FILE = "/content/drive/MyDrive/Exoplanet_Dataset/11_Training_Dataset_V2/Training_Dataset_V2.csv"

training_dataset_v2.to_csv(

    OUTPUT_FILE,

    index=False

)

print("Saved Successfully!")
print(OUTPUT_FILE)

Saved Successfully!
/content/drive/MyDrive/Exoplanet_Dataset/11_Training_Dataset_V2/Training_Dataset_V2.csv